projects:
<<<<<<< HEAD
  prompty:
=======
  prompt:
>>>>>>> development
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
<<<<<<< HEAD
=======
extensions:
  amplify:
    version: 3
>>>>>>> development
